title: Zhi Research Docs
description: Zhi Research Docs
theme: just-the-docs

url: https://akiitr.github.io/zhi_research/

aux_links:
  Template Repository: https://akiitr.github.io/zhi_research/

# Default for all the pages
defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "default"
      author: "Anubhav"

# Mermaid for flow charts
mermaid:
  version: "11.11.0"

# Search settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true # Set to true to allow users to easily access search

# For copy button on code
enable_copy_code_button: true

# Heading anchors
heading_anchors: true

# Footer content
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2024-2030 Anubhav Kumar. Distributed by an <a href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT license</a>.'

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y at %I:%M %p"

# GitHub edit link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://akiitr.github.io/zhi_research/"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Color scheme
color_scheme: dark

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

# Kramdown settings
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# HTML compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Enable KaTeX for modern math rendering (optional)
katex:
  enabled: true
